# This file was generated by GoReleaser. DO NOT EDIT.
cask "fabrika" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "9e92c20ef511e3c22030f8329e38e3085ce836867a2dae2f6da68dabf06861f1"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b6ff034a8b7a2e5b2cc7f078c776aa09bfe90f8698ef6ae9e2bb2680640eeb9"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b66434a1f64f30975063acff1b836f7df8c47af59953330fc0f4f9227ef176b6"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ffdf2ebef16c585bd389854eed97cb29d48bacd4e6058d8344f710a121eea01b"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_linux_arm64.tar.gz"
    end
  end

  name "fabrika"
  desc "Single Go binary orchestrating local coding agents."
  homepage "https://github.com/berkaycubuk/fabrika"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fabrika"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fabrika"]
    end
  end

  # No zap stanza required

end
