# This file was generated by GoReleaser. DO NOT EDIT.
cask "fabrika" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "a12416089df25f2d235a57eb4d6f822fc5c213677186a8a0b7b8686f80d7affe"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "963227cb926746e1a2e8334851def97e841720a976001f32e0e721eae1024dfe"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9a51315a86721fca33a9694299bc357f1cb34f1c33244dbd71aa0aa26596a775"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "285cd7469a58cc9849bfb88e430fa2abf85d6e40b04c2b7b9eb984529f5b8367"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_linux_arm64.tar.gz"
    end
  end

  name "fabrika"
  desc "Single Go binary orchestrating local coding agents."
  homepage "https://github.com/berkaycubuk/fabrika"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fabrika"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fabrika"]
    end
  end

  # No zap stanza required

end
