# This file was generated by GoReleaser. DO NOT EDIT.
cask "fabrika" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "912f9bd86ec76b263036401e56f7ee7acc34b36f6ab5717044d89cf13e157b60"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d692a7e979c119e4e2fd50cd9e23385e46886ef659bfe637bdce31d706aee2a1"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65f6aab1db57f73d6e2d3f3c92d52b77209f137324a9fa84ca52b814e538b207"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e130f0ce3b2df531158d91d65c32506d2740c2172fa75f2aaa2ecf905fa0937f"
      url "https://github.com/berkaycubuk/fabrika/releases/download/v#{version}/fabrika_linux_arm64.tar.gz"
    end
  end

  name "fabrika"
  desc "Single Go binary orchestrating local coding agents."
  homepage "https://github.com/berkaycubuk/fabrika"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fabrika"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fabrika"]
    end
  end

  # No zap stanza required

end
